# Ejemplo de red neuronal con Keras

In [ ]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

Cargar el conjunto de datos

In [ ]:
datos = loadtxt('xor.csv',delimiter=',')

Dividir en datos de entrada (X) y de salida (y)

In [ ]:
X = datos[:,0:2]
y = datos[:,2]

In [ ]:
X

array([[1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
y

array([0., 1., 1., 0.])

Definir el modelo con keras

In [ ]:
modelo = Sequential()

In [ ]:
modelo.add(Dense(10,input_dim=2,activation='relu'))
modelo.add(Dense(10,activation='relu'))
modelo.add(Dense(8,activation='relu'))
modelo.add(Dense(1,activation='sigmoid'))

Compilar el modelo keras

In [ ]:
modelo.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

Entrenar el modelo con el conjunto de datos

In [ ]:
modelo.fit(X,y,epochs=1000,batch_size=1,verbose=0)

Evaluar el modelo keras

In [ ]:
_ , accuracy = modelo.evaluate(X,y)
print('Exactitud (accuracy): %.2f' % (accuracy*100))

1/1 [==============================] - 0s 153ms/step - loss: 4.7174e-04 - accuracy: 1.0000
Exactitud (accuracy): 100.00


Realizar predicciones con el modelo

In [ ]:
predicciones = modelo.predict(X)

Los resultados verdaderos

In [ ]:
y

array([0., 1., 1., 0.])

Los resultados predichos

In [ ]:
predicciones

array([[8.3383886e-05],
       [9.9966395e-01],
       [9.9983066e-01],
       [1.2972951e-03]], dtype=float32)

comparaciones

In [ ]:
for i in range(4):
  print('%s => %.2f (esperado %d))' % (X[i].tolist(),predicciones[i],y[i]))

[1.0, 1.0] => 0.00 (esperado 0))
[1.0, 0.0] => 1.00 (esperado 1))
[0.0, 1.0] => 1.00 (esperado 1))
[0.0, 0.0] => 0.00 (esperado 0))
