# Ejemplo de red neuronal con Keras

In [ ]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

Cargar el conjunto de datos

In [ ]:
datos = loadtxt('xor.csv',delimiter=',')

Dividir en datos de entrada (X) y de salida (y)

In [ ]:
X = datos[:,0:2]
y = datos[:,2]

In [ ]:
X

array([[1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
y

array([0., 1., 1., 0.])

Definir el modelo con keras

In [ ]:
modelo = Sequential()

In [ ]:
modelo.add(Dense(3,input_dim=2,activation='sigmoid'))
modelo.add(Dense(1,activation='sigmoid'))

Compilar el modelo keras

In [ ]:
modelo.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

Entrenar el modelo con el conjunto de datos

In [ ]:
modelo.fit(X,y,epochs=2000,batch_size=1,verbose=0)

Evaluar el modelo keras

In [ ]:
_ , accuracy = modelo.evaluate(X,y)
print('Exactitud (accuracy): %.2f' % (accuracy*100))

1/1 [==============================] - 0s 110ms/step - loss: 0.6850 - accuracy: 0.5000
Exactitud (accuracy): 50.00


Realizar predicciones con el modelo

In [ ]:
predicciones = modelo.predict(X)

Los resultados verdaderos

In [ ]:
y

array([0., 1., 1., 0.])

Los resultados predichos

In [ ]:
predicciones

array([[0.52351016],
       [0.48789832],
       [0.5233607 ],
       [0.46929553]], dtype=float32)

comparaciones

In [ ]:
for i in range(4):
  print('%s => %.2f (esperado %d))' % (X[i].tolist(),predicciones[i],y[i]))

[1.0, 1.0] => 0.52 (esperado 0))
[1.0, 0.0] => 0.49 (esperado 1))
[0.0, 1.0] => 0.52 (esperado 1))
[0.0, 0.0] => 0.47 (esperado 0))
